name: Download Valmikinagar Roll via API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 02:00 UTC

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download roll ZIP via API
        run: python download_zip_api.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: valmikinagar-roll
          path: valmikinagar.zip
