name: Download  Roll via API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright chromium 

      - name: Download roll ZIP via API
        run: python Parser.py
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
            name: screenshots
            path: screenshots
      name: Playwright Screenshot Capture

on:
  push:
    branches:
      - main

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run script
        run: python your_script.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: screenshots/
