# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Playwright and dependencies
      run: |
          pip install --upgrade pip
          pip install playwright
          # installs browsers + necessary libs on Ubuntu
          playwright install --with-deps

    - name: Run download script
      run: |
          python Parser.py

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
          name: valmikinagar-roll
          path: valmikinagar.zip
