name: Download Roll via API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  download-roll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
        
      - name: Run Parser script
        run:  xvfb-run -a python Parser.py

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload screenshots on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
